// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrazdrqexmpyavperkmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYXpkcnFleG1weWF2cGVya212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTcwNjgsImV4cCI6MjA2ODg5MzA2OH0.173t2y7rEVl0UkPZc8EDHH9HZA6FqG3oqEKrpACU15Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});